
// =========================================================
// ProcessIQ — mock data (sector salud)
// =========================================================

const ROLES = {
  director: {
    id: "director",
    name: "Dra. María Restrepo",
    title: "Directora de Operaciones",
    initials: "MR",
    org: "Red Salud Norte · Bogotá",
    permissions: ["dashboard", "insights", "analytics", "processes", "automations", "reports", "config"],
    focus: "kpi-estrategico",
  },
  manager: {
    id: "manager",
    name: "Carlos Vega",
    title: "Gerente Urgencias",
    initials: "CV",
    org: "Hospital Universitario",
    permissions: ["dashboard", "insights", "analytics", "processes", "reports"],
    focus: "operativo",
  },
  analyst: {
    id: "analyst",
    name: "Daniela Sánchez",
    title: "Analista de Procesos",
    initials: "DS",
    org: "BPM & Mejora Continua",
    permissions: ["dashboard", "insights", "analytics", "processes", "automations", "reports"],
    focus: "analitico",
  },
};

const KPI_DEFS = [
  {
    id: "throughput",
    label: "Procesos completados",
    value: "12,840",
    raw: 12840,
    delta: "+8.4%",
    deltaDir: "up",
    sub: "vs. mes anterior",
    spark: [22, 28, 24, 30, 32, 30, 38, 42, 40, 46, 50, 54],
    tone: "accent",
    icon: "activity",
    tooltip: "Volumen total de procesos finalizados en el período seleccionado.",
  },
  {
    id: "cycle",
    label: "Tiempo de ciclo",
    value: "3.2",
    unit: "h",
    delta: "-12%",
    deltaDir: "up",
    sub: "promedio ponderado",
    spark: [42, 40, 38, 36, 34, 35, 33, 32, 30, 32, 31, 30],
    tone: "success",
    icon: "clock",
    tooltip: "Duración media ponderada de los procesos críticos.",
  },
  {
    id: "sla",
    label: "Cumplimiento SLA",
    value: "96.4",
    unit: "%",
    delta: "+3.1 pts",
    deltaDir: "up",
    sub: "objetivo 95%",
    spark: [88, 89, 90, 91, 93, 92, 94, 94, 95, 95, 96, 96.4],
    tone: "success",
    icon: "shield",
    tooltip: "Procesos completados dentro del acuerdo de nivel de servicio.",
  },
  {
    id: "incidents",
    label: "Incidencias críticas",
    value: "14",
    delta: "+2",
    deltaDir: "down",
    sub: "8 sin resolver",
    spark: [6, 8, 5, 9, 7, 11, 10, 9, 12, 13, 12, 14],
    tone: "danger",
    icon: "alert",
    tooltip: "Eventos que detuvieron o degradaron procesos críticos.",
  },
  {
    id: "automation",
    label: "ROI Automatización",
    value: "$284K",
    delta: "+$42K",
    deltaDir: "up",
    sub: "potencial anual",
    spark: [10, 14, 18, 22, 26, 30, 36, 40, 48, 55, 64, 72],
    tone: "ai",
    icon: "sparkle",
    tooltip: "Ahorro estimado por automatizaciones aprobadas y proyectadas.",
  },
];

// Productividad y eficiencia temporal — series mensuales
const PRODUCTIVITY_SERIES = {
  weekly: {
    labels: ["L", "M", "X", "J", "V", "S", "D"],
    throughput: [380, 420, 460, 510, 530, 280, 210],
    sla: [92, 93, 94, 95, 96, 91, 90],
    cycle: [4.1, 3.9, 3.7, 3.4, 3.2, 4.0, 4.2],
  },
  monthly: {
    labels: ["Sem 1", "Sem 2", "Sem 3", "Sem 4"],
    throughput: [2840, 3120, 3340, 3540],
    sla: [93.2, 94.6, 95.4, 96.4],
    cycle: [3.8, 3.5, 3.3, 3.2],
  },
  quarterly: {
    labels: ["Ene", "Feb", "Mar", "Abr", "May"],
    throughput: [10240, 10980, 11420, 12100, 12840],
    sla: [91.2, 92.4, 93.8, 95.1, 96.4],
    cycle: [4.4, 4.1, 3.8, 3.5, 3.2],
  },
};

const PROCESSES = [
  {
    id: "P-001",
    name: "Admisión Urgencias",
    area: "Urgencias",
    owner: "Dra. L. Pardo",
    avgCycle: 0.7,
    slaTarget: 1.0,
    slaActual: 97.2,
    volume: 4820,
    bottleneck: "Triaje",
    status: "ok",
    risk: 18,
    trend: [62, 60, 58, 55, 52, 50, 48],
    aiFlag: null,
    automationOpp: 92,
  },
  {
    id: "P-002",
    name: "Programación cirugía electiva",
    area: "Quirófano",
    owner: "Dr. F. Morales",
    avgCycle: 38,
    slaTarget: 24,
    slaActual: 78.4,
    volume: 612,
    bottleneck: "Autorización aseguradora",
    status: "risk",
    risk: 72,
    trend: [30, 34, 38, 42, 40, 44, 48],
    aiFlag: { type: "bottleneck", label: "Cuello de botella crítico" },
    automationOpp: 88,
  },
  {
    id: "P-003",
    name: "Conciliación medicamentos",
    area: "Farmacia",
    owner: "QF. R. Bedoya",
    avgCycle: 2.4,
    slaTarget: 4.0,
    slaActual: 94.6,
    volume: 1840,
    bottleneck: "Validación clínica",
    status: "ok",
    risk: 22,
    trend: [40, 42, 38, 36, 36, 34, 32],
    aiFlag: null,
    automationOpp: 65,
  },
  {
    id: "P-004",
    name: "Alta hospitalaria",
    area: "Hospitalización",
    owner: "Enf. M. Torres",
    avgCycle: 5.8,
    slaTarget: 4.0,
    slaActual: 71.2,
    volume: 2240,
    bottleneck: "Cuenta cobro + receta",
    status: "risk",
    risk: 68,
    trend: [50, 52, 54, 58, 60, 62, 64],
    aiFlag: { type: "trend", label: "Tendencia al alza" },
    automationOpp: 95,
  },
  {
    id: "P-005",
    name: "Facturación EPS",
    area: "Administrativa",
    owner: "L. Galindo",
    avgCycle: 72,
    slaTarget: 48,
    slaActual: 64.8,
    volume: 980,
    bottleneck: "Glosas y devoluciones",
    status: "critical",
    risk: 84,
    trend: [60, 64, 68, 70, 72, 76, 78],
    aiFlag: { type: "anomaly", label: "Anomalía detectada" },
    automationOpp: 97,
  },
  {
    id: "P-006",
    name: "Agendamiento consulta externa",
    area: "Ambulatoria",
    owner: "P. Romero",
    avgCycle: 0.4,
    slaTarget: 0.5,
    slaActual: 98.8,
    volume: 6420,
    bottleneck: "—",
    status: "ok",
    risk: 8,
    trend: [12, 10, 11, 10, 9, 9, 8],
    aiFlag: null,
    automationOpp: 40,
  },
  {
    id: "P-007",
    name: "Resultados laboratorio",
    area: "Laboratorio",
    owner: "Bact. S. Rincón",
    avgCycle: 3.6,
    slaTarget: 4.0,
    slaActual: 92.1,
    volume: 3120,
    bottleneck: "Confirmación crítica",
    status: "warn",
    risk: 34,
    trend: [28, 26, 26, 24, 22, 24, 22],
    aiFlag: null,
    automationOpp: 78,
  },
  {
    id: "P-008",
    name: "Referencia y contrarreferencia",
    area: "Coordinación",
    owner: "Dr. A. Castaño",
    avgCycle: 14,
    slaTarget: 8,
    slaActual: 76.2,
    volume: 412,
    bottleneck: "Disponibilidad red externa",
    status: "warn",
    risk: 58,
    trend: [42, 44, 46, 48, 50, 52, 54],
    aiFlag: { type: "trend", label: "Riesgo creciente" },
    automationOpp: 72,
  },
];

const AI_INSIGHTS = [
  {
    id: "i-01",
    priority: "high",
    impact: "$48K/mes",
    category: "Cuello de botella",
    title: "Autorización aseguradora retrasa 38% de cirugías electivas",
    detail:
      "La etapa de autorización promedia 28h frente a un SLA de 12h. Afecta principalmente a tres aseguradoras y se concentra los lunes y martes.",
    confidence: 0.94,
    actions: ["Crear automatización", "Asignar a Carlos Vega", "Generar reporte"],
    related: "P-002",
    eta: "Implementable en 2 semanas",
  },
  {
    id: "i-02",
    priority: "high",
    impact: "$31K/mes",
    category: "Anomalía",
    title: "Glosas de facturación aumentaron 22% en últimas 3 semanas",
    detail:
      "El patrón coincide con cambios en codificación CUPS. Recomendamos validación previa automatizada antes del envío al EPS.",
    confidence: 0.91,
    actions: ["Crear regla de validación", "Notificar a L. Galindo"],
    related: "P-005",
    eta: "Disponible para producción",
  },
  {
    id: "i-03",
    priority: "med",
    impact: "$18K/mes",
    category: "Automatización",
    title: "Alta hospitalaria puede automatizarse en 60% (cuenta + receta)",
    detail:
      "El sub-proceso de generación de cuenta de cobro y receta de egreso es altamente repetitivo y susceptible a RPA + LLM para resumen clínico.",
    confidence: 0.87,
    actions: ["Diseñar piloto", "Estimar ROI detallado"],
    related: "P-004",
    eta: "Piloto en 4 semanas",
  },
  {
    id: "i-04",
    priority: "med",
    impact: "+4.2 pts SLA",
    category: "Tendencia",
    title: "Triaje en urgencias mejora consistentemente con nuevo turno",
    detail:
      "Desde la rotación del 14 de mayo, el tiempo de triaje disminuyó 18% sin impacto adverso en satisfacción.",
    confidence: 0.82,
    actions: ["Replicar en sede sur", "Documentar buena práctica"],
    related: "P-001",
    eta: "Replicable",
  },
  {
    id: "i-05",
    priority: "low",
    impact: "—",
    category: "Riesgo",
    title: "Sobrecarga proyectada en laboratorio para próximo fin de semana",
    detail:
      "Modelo predictivo anticipa un incremento de 28% en órdenes urgentes basado en patrones estacionales y campaña de prevención.",
    confidence: 0.74,
    actions: ["Asignar turno extra", "Avisar a Bact. S. Rincón"],
    related: "P-007",
    eta: "Preventivo",
  },
];

const AUTOMATIONS = [
  {
    id: "A-001", name: "Validación CUPS pre-envío EPS", status: "active",
    process: "Facturación EPS", trigger: "Antes de envío a aseguradora",
    runs: 1240, savings: 18400, satisfaction: 96, owner: "L. Galindo",
    type: "LLM + reglas", lastRun: "hace 14 min",
  },
  {
    id: "A-002", name: "Resumen clínico de egreso", status: "active",
    process: "Alta hospitalaria", trigger: "Al cierre de historia clínica",
    runs: 820, savings: 12800, satisfaction: 91, owner: "Enf. M. Torres",
    type: "LLM", lastRun: "hace 32 min",
  },
  {
    id: "A-003", name: "Triage asistido por IA", status: "active",
    process: "Admisión Urgencias", trigger: "Al ingreso del paciente",
    runs: 4640, savings: 22100, satisfaction: 94, owner: "Dra. L. Pardo",
    type: "Clasificación ML", lastRun: "hace 2 min",
  },
  {
    id: "A-004", name: "Seguimiento de glosas", status: "draft",
    process: "Facturación EPS", trigger: "Glosa recibida",
    runs: 0, savings: 0, satisfaction: 0, owner: "—",
    type: "Workflow", lastRun: "—",
  },
  {
    id: "A-005", name: "Recordatorio post-consulta", status: "paused",
    process: "Consulta externa", trigger: "+48h después de la consulta",
    runs: 6840, savings: 4200, satisfaction: 88, owner: "P. Romero",
    type: "Workflow", lastRun: "ayer",
  },
];

const REPORTS = [
  {
    id: "R-2026-05-22", title: "Resumen semanal Dirección Operativa",
    period: "12 — 18 mayo 2026", author: "ProcessIQ · GPT-Ops 4",
    status: "ready", pages: 12, audience: "Comité directivo",
    summary:
      "El cumplimiento de SLA cierra la semana en 96.4% (+3.1 pts vs. semana previa). Persisten dos cuellos de botella: autorización aseguradora y conciliación de glosas EPS, ambos con planes de automatización en curso.",
    sections: ["KPIs ejecutivos", "Cuellos de botella", "Automatizaciones activas", "Incidencias", "Proyección semanal", "Acciones recomendadas"],
  },
  {
    id: "R-2026-05-15", title: "Análisis trimestral Urgencias",
    period: "Q1 2026", author: "ProcessIQ · GPT-Ops 4",
    status: "ready", pages: 28, audience: "Gerencia Urgencias",
    summary:
      "Mejora sostenida del 18% en tiempo de triaje y reducción del 9% en reingresos a 72h. Recomendamos consolidar el nuevo modelo de turnos y replicarlo a sede sur.",
    sections: ["Volumen y demanda", "Triaje", "Salidas y reingresos", "Recursos", "Proyecciones"],
  },
  {
    id: "R-2026-05-08", title: "Auditoría ciclo de facturación EPS",
    period: "Abril 2026", author: "ProcessIQ · GPT-Ops 4",
    status: "ready", pages: 18, audience: "Dirección financiera",
    summary:
      "El ciclo facturación → conciliación aumentó 22% por glosas. Identificamos 3 patrones recurrentes y proponemos validación pre-envío automatizada.",
    sections: ["Resumen", "Patrones de glosa", "Top aseguradoras", "Plan de mitigación"],
  },
];

const INCIDENTS = [
  { id: "INC-2841", title: "Caída de integración HL7 con laboratorio externo", severity: "high", time: "hace 12 min", area: "Laboratorio", status: "open" },
  { id: "INC-2840", title: "Pico de espera en triaje (>45 min)", severity: "med", time: "hace 38 min", area: "Urgencias", status: "ack" },
  { id: "INC-2839", title: "Retraso en validación de glosas EPS Sanitas", severity: "med", time: "hace 1 h", area: "Administrativa", status: "open" },
  { id: "INC-2838", title: "Falla módulo de receta electrónica", severity: "high", time: "hace 3 h", area: "Hospitalización", status: "resolved" },
];

const ACTIVITY_FEED = [
  { who: "ProcessIQ AI", what: "generó un reporte semanal de dirección operativa", when: "hace 4 min", kind: "ai" },
  { who: "C. Vega", what: "aprobó automatización 'Validación CUPS pre-envío'", when: "hace 28 min", kind: "human" },
  { who: "ProcessIQ AI", what: "detectó anomalía en glosas EPS", when: "hace 42 min", kind: "ai" },
  { who: "M. Torres", what: "cerró 4 incidencias en Hospitalización", when: "hace 1 h", kind: "human" },
  { who: "ProcessIQ AI", what: "recomendó replicar buena práctica de triaje a sede sur", when: "hace 2 h", kind: "ai" },
];

const AREAS = [
  { id: "urgencias",      name: "Urgencias",        load: 84, sla: 92.1, incidents: 4, color: "danger" },
  { id: "quirofano",      name: "Quirófano",        load: 71, sla: 78.4, incidents: 2, color: "warning" },
  { id: "hospitalizacion",name: "Hospitalización",  load: 66, sla: 87.5, incidents: 3, color: "warning" },
  { id: "ambulatoria",    name: "Consulta externa", load: 58, sla: 98.8, incidents: 0, color: "success" },
  { id: "farmacia",       name: "Farmacia",         load: 52, sla: 94.6, incidents: 1, color: "success" },
  { id: "laboratorio",    name: "Laboratorio",      load: 62, sla: 92.1, incidents: 2, color: "warning" },
  { id: "administrativa", name: "Administrativa",   load: 48, sla: 64.8, incidents: 6, color: "danger" },
  { id: "coordinacion",   name: "Coordinación",     load: 40, sla: 76.2, incidents: 1, color: "warning" },
];

const AI_SUGGESTED_PROMPTS = [
  "¿Cuál fue el cuello de botella más costoso este mes?",
  "Compara la productividad de Urgencias vs. Hospitalización",
  "Genera un reporte para el comité directivo del viernes",
  "¿Qué automatizaciones tienen mayor ROI proyectado?",
  "Resume las incidencias críticas de hoy",
];

export { ROLES, KPI_DEFS, PRODUCTIVITY_SERIES, PROCESSES, AI_INSIGHTS, AUTOMATIONS, REPORTS, INCIDENTS, ACTIVITY_FEED, AREAS, AI_SUGGESTED_PROMPTS };
